CREATE TABLE IF NOT EXISTS mpa_type
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255)
);

CREATE TABLE IF NOT EXISTS films
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255),
    description varchar(255),
    releaseDate date,
    duration    bigint,
    mpa_Id      bigint REFERENCES mpa_type (id)
);

CREATE TABLE IF NOT EXISTS users
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(255),
    login    varchar(255),
    name     varchar(255),
    birthday date
);

CREATE TABLE IF NOT EXISTS likes
(
    film_id bigint REFERENCES films (id),
    user_id bigint REFERENCES users (id),
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS genre_type
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255)
);

CREATE TABLE IF NOT EXISTS film_genres
(
    film_id  bigint REFERENCES films (id),
    genre_id bigint REFERENCES genre_type (id),
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS friends
(
    user_id   bigint REFERENCES users (id),
    friend_id bigint REFERENCES users (id),
    PRIMARY KEY (user_id, friend_id)
);